name: update readme doc

on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        
      - name: 'Get previous release tag'
        id: tag
        uses: "sammcoe/get-previous-release-action@v1"

      - name: replace version
        run: sed -i "s/${{steps.tag.outputs.tag}}/${{steps.previoustag.outputs.tag}}/g" README*.md

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update report
          signoff: false
          branch: doc/${{steps.previoustag.outputs.tag}}
          base: main
          delete-branch: true
          title: 'doc: Update README files version'
          body: |
            **在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**

            - [x] 标题为fix、feat或doc开头
            - [x] 我已检查没有与此请求重复的拉取请求。
            - [x] 我已经考虑过，并确认这份呈件对其他人很有价值。
            - [x] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。

            **填写PR内容：**
            Update README files version to latest tag by bot 🚀.
          draft: false
